CREATE TABLE block (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT NOT NULL,
    parent_block_id BIGINT,
    type VARCHAR(30) NOT NULL,
    props JSONB NOT NULL,
    position VARCHAR(64) NOT NULL,
    version INTEGER NOT NULL DEFAULT 0,
    is_trashed BOOLEAN NOT NULL DEFAULT FALSE,
    created_by BIGINT NOT NULL,
    updated_by BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT fk_block_workspace_id FOREIGN KEY (workspace_id) REFERENCES workspace(id) ON DELETE CASCADE,
    CONSTRAINT fk_block_parent_block_id FOREIGN KEY (parent_block_id) REFERENCES block(id) ON DELETE CASCADE,
    CONSTRAINT fk_block_created_by FOREIGN KEY (created_by) REFERENCES "user"(id),
    CONSTRAINT fk_block_updated_by FOREIGN KEY (updated_by) REFERENCES "user"(id)
);

CREATE INDEX idx_block_workspace_id
    ON block(workspace_id);

CREATE INDEX idx_block_parent_block_id_position
    ON block(parent_block_id, position);
    