spring:
  application:
    name: kiroku

  datasource:
    url: jdbc:postgresql://postgres:5432/kiroku
    username: kiroku
    password: password
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true