### Login (success)
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "1234"
}


### Login (wrong password)
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "wrong-password"
}


### Login (unknown email)
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "unknown@test.com",
  "password": "1234"
}


### Logout (success, accessToken input)
POST http://localhost:8080/api/auth/logout
Cookie: access_token=


### Logout (no cookie)
POST http://localhost:8080/api/auth/logout
