### Create User
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "1234",
  "nickname": "lee"
}


### Get User
GET http://localhost:8080/api/users/1


### Get User (forbidden, not self)
GET http://localhost:8080/api/users/2


### Update Nickname
PATCH http://localhost:8080/api/users/1
Content-Type: application/json

{
  "nickname": "lee2"
}


### Clear Nickname (null check)
PATCH http://localhost:8080/api/users/1
Content-Type: application/json

{
  "nickname": null
}


### Update Nickname (forbidden, not self)
PATCH http://localhost:8080/api/users/2
Content-Type: application/json

{
  "nickname": "hacked"
}


### Change Password
PATCH http://localhost:8080/api/users/1/password
Content-Type: application/json

{
  "password": "1234"
}


### Delete User
DELETE http://localhost:8080/api/users/1