### Create User
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "1234",
  "nickname": "lee"
}


### Get User
GET http://localhost:8080/api/users/1


### Get Users
GET http://localhost:8080/api/users


### Delete User
DELETE http://localhost:8080/api/users/1